title:  "Waterflame Blogs"
tagline: "The blog of a random internet user"
description: "The blog of a random internet user"
author:
  twitter: waterflame321

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'wblog-1'

menu:
- {name: 'Rambles', file: 'rambles'}
- {name: 'Reviews', file: 'reviews'}
- {name: 'Showcase', file: 'showcase'}

social:
- {icon: 'twitter', link: '/pages/social'}
- {icon: 'envelope', link: '/pages/social'}
- {icon: 'rss', link: '/feed'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
