title:  "Water Blogs"
tagline: "The blog of a random internet user"
description: "The blog of a random internet user"
author:
  twitter: waterflame321

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'wblog-1'

menu:
- {name: 'Rambles', file: 'rambles.html'}
- {name: 'Book Reviews', file: 'books.html'}
- {name: 'Game Reviews', file: 'games.html'}
- {name: 'Showcase', file: 'showcase.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/waterflame321'}
- {icon: 'envelope', link: '/feed'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
